using BanallyMe.UnException.Swashbuckle.OperationFilters;
using Microsoft.Extensions.DependencyInjection;

namespace BanallyMe.UnException.Swashbuckle.DependencyInjection
{
    /// <summary>
    /// Provides extensions to add responses generated by UnException to the swagger documentation
    /// generated by Swashbuckle.AspNetCore.
    /// </summary>
    public static class UnExceptionSwashbuckleLoader
    {
        /// <summary>
        /// Adds a filter to SwaggerGen, which adds automatic responses of UnException to the documentation.
        /// </summary>
        /// <param name="services">Collection of services used to build the ASP.NET Core dependency injection container.</param>
        public static void AddUnExceptionToSwashbuckle(this IServiceCollection services)
        {
            services.ConfigureSwaggerGen(options => options.OperationFilter<ReplyOnExceptionOperationFilter>());
        }
    }
}
